-- ============================================================
-- SQL SCHEMA FOR NEW FEATURES: ATTENDANCE, EXAMS, SUBJECTS, MARKS
-- Run this in your Supabase SQL Editor
-- ============================================================

-- 1. Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    date TEXT NOT NULL, -- Format DD-MM-YYYY
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent', 'Leave')),
    marked_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_student_attendance_per_day UNIQUE(school_id, student_id, date)
);

-- 2. Exams Table
CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    exam_name TEXT NOT NULL,
    term TEXT,
    class TEXT,
    date TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT,
    category TEXT DEFAULT 'Compulsory',
    total_marks NUMERIC(6, 2) DEFAULT 100,
    passing_marks NUMERIC(6, 2) DEFAULT 33,
    class TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_subject_name UNIQUE (school_id, name)
);

-- 4. Marks Table
CREATE TABLE IF NOT EXISTS marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    exam_id BIGINT REFERENCES exams(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
    total_marks NUMERIC(6, 2) NOT NULL DEFAULT 100,
    obtained_marks NUMERIC(6, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_student_exam_subject_mark UNIQUE(school_id, student_id, exam_id, subject_id)
);

-- Enable RLS & Policies
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE marks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for attendance" ON attendance;
CREATE POLICY "Allow all for attendance" ON attendance FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for exams" ON exams;
CREATE POLICY "Allow all for exams" ON exams FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for subjects" ON subjects;
CREATE POLICY "Allow all for subjects" ON subjects FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for marks" ON marks;
CREATE POLICY "Allow all for marks" ON marks FOR ALL USING (true) WITH CHECK (true);

-- 5. Admissions Table (Public Online Admission Form)
CREATE TABLE IF NOT EXISTS admissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_name TEXT NOT NULL,
    father_name TEXT NOT NULL,
    dob TEXT,
    gender TEXT,
    class_applying TEXT NOT NULL,
    previous_school TEXT,
    phone TEXT NOT NULL,
    address TEXT,
    photo_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, approved, rejected
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Homework Diary Table
CREATE TABLE IF NOT EXISTS homework (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class TEXT NOT NULL,
    subject TEXT NOT NULL,
    date TEXT NOT NULL, -- DD-MM-YYYY
    due_date TEXT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE homework ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for admissions" ON admissions;
CREATE POLICY "Allow all for admissions" ON admissions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for homework" ON homework;
CREATE POLICY "Allow all for homework" ON homework FOR ALL USING (true) WITH CHECK (true);

-- 7. Class Subjects Mapping Table (Many-to-Many Class to Subjects)
CREATE TABLE IF NOT EXISTS class_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class_name TEXT NOT NULL,
    subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_class_subject UNIQUE (school_id, class_name, subject_id)
);

ALTER TABLE class_subjects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for class_subjects" ON class_subjects;
CREATE POLICY "Allow all for class_subjects" ON class_subjects FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 8. NSB CASH BOOK (Form No 8)
-- ============================================================
CREATE TABLE IF NOT EXISTS nsb_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    emis TEXT,
    tehsil TEXT,
    zila TEXT,
    school_name TEXT,
    bank_name TEXT,
    account_no TEXT,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    previous_balance NUMERIC(12, 2) DEFAULT 0,
    bank_balance NUMERIC(12, 2) DEFAULT 0,
    cash_in_hand NUMERIC(12, 2) DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_nsb_settings UNIQUE (school_id, month, year)
);

CREATE TABLE IF NOT EXISTS nsb_income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    sr_no INT,
    date TEXT NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_mode TEXT DEFAULT 'چیک',
    signature TEXT DEFAULT 'منظور',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS nsb_expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    sr_no INT,
    date TEXT NOT NULL,
    receipt_no TEXT,
    description TEXT NOT NULL,
    bank_withdrawn NUMERIC(12, 2) DEFAULT 0,
    payment NUMERIC(12, 2) NOT NULL DEFAULT 0,
    approval_ref TEXT,
    signature TEXT DEFAULT 'منظور',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE nsb_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE nsb_income ENABLE ROW LEVEL SECURITY;
ALTER TABLE nsb_expense ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for nsb_settings" ON nsb_settings;
CREATE POLICY "Allow all for nsb_settings" ON nsb_settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for nsb_income" ON nsb_income;
CREATE POLICY "Allow all for nsb_income" ON nsb_income FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for nsb_expense" ON nsb_expense;
CREATE POLICY "Allow all for nsb_expense" ON nsb_expense FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 9. FTF REGISTER (فروغ تعلیم فنڈ)
-- ============================================================
CREATE TABLE IF NOT EXISTS ftf_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    markaz TEXT,
    tehsil TEXT,
    zila TEXT,
    school_name TEXT,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    babat_maah TEXT,
    previous_balance NUMERIC(12, 2) DEFAULT 0,
    cash_in_hand NUMERIC(12, 2) DEFAULT 0,
    bank_balance NUMERIC(12, 2) DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_ftf_settings UNIQUE (school_id, month, year)
);

CREATE TABLE IF NOT EXISTS ftf_fee_structure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class_name TEXT NOT NULL,
    fee_amount NUMERIC(10, 2) NOT NULL DEFAULT 20,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_ftf_fee UNIQUE (school_id, class_name)
);

CREATE TABLE IF NOT EXISTS ftf_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    class_name TEXT NOT NULL,
    student_count INT NOT NULL DEFAULT 0,
    fee_per_student NUMERIC(10, 2) NOT NULL DEFAULT 20,
    total_collected NUMERIC(12, 2) NOT NULL DEFAULT 0,
    teacher_signature TEXT,
    receiver_signature TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_ftf_collection UNIQUE (school_id, month, year, class_name)
);

CREATE TABLE IF NOT EXISTS ftf_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    date TEXT NOT NULL,
    tafseel TEXT NOT NULL,
    raqam NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ftf_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE ftf_fee_structure ENABLE ROW LEVEL SECURITY;
ALTER TABLE ftf_collection ENABLE ROW LEVEL SECURITY;
ALTER TABLE ftf_expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for ftf_settings" ON ftf_settings;
CREATE POLICY "Allow all for ftf_settings" ON ftf_settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for ftf_fee_structure" ON ftf_fee_structure;
CREATE POLICY "Allow all for ftf_fee_structure" ON ftf_fee_structure FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for ftf_collection" ON ftf_collection;
CREATE POLICY "Allow all for ftf_collection" ON ftf_collection FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for ftf_expenses" ON ftf_expenses;
CREATE POLICY "Allow all for ftf_expenses" ON ftf_expenses FOR ALL USING (true) WITH CHECK (true);

