-- ============================================================
-- SQL SCHEMA FOR NEW FEATURES: ATTENDANCE, EXAMS, SUBJECTS, MARKS
-- Run this in your Supabase SQL Editor
-- ============================================================

-- 1. Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    date TEXT NOT NULL, -- Format DD-MM-YYYY
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent', 'Leave')),
    marked_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_student_attendance_per_day UNIQUE(school_id, student_id, date)
);

-- 2. Exams Table
CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    exam_name TEXT NOT NULL,
    term TEXT,
    class TEXT,
    date TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT,
    category TEXT DEFAULT 'Compulsory',
    total_marks NUMERIC(6, 2) DEFAULT 100,
    passing_marks NUMERIC(6, 2) DEFAULT 33,
    class TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_subject_name UNIQUE (school_id, name)
);

-- 4. Marks Table
CREATE TABLE IF NOT EXISTS marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    exam_id BIGINT REFERENCES exams(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
    total_marks NUMERIC(6, 2) NOT NULL DEFAULT 100,
    obtained_marks NUMERIC(6, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_student_exam_subject_mark UNIQUE(school_id, student_id, exam_id, subject_id)
);

-- Enable RLS & Policies
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE marks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for attendance" ON attendance;
CREATE POLICY "Allow all for attendance" ON attendance FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for exams" ON exams;
CREATE POLICY "Allow all for exams" ON exams FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for subjects" ON subjects;
CREATE POLICY "Allow all for subjects" ON subjects FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for marks" ON marks;
CREATE POLICY "Allow all for marks" ON marks FOR ALL USING (true) WITH CHECK (true);

-- 5. Admissions Table (Public Online Admission Form)
CREATE TABLE IF NOT EXISTS admissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_name TEXT NOT NULL,
    father_name TEXT NOT NULL,
    dob TEXT,
    gender TEXT,
    class_applying TEXT NOT NULL,
    previous_school TEXT,
    phone TEXT NOT NULL,
    address TEXT,
    photo_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, approved, rejected
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Homework Diary Table
CREATE TABLE IF NOT EXISTS homework (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class TEXT NOT NULL,
    subject TEXT NOT NULL,
    date TEXT NOT NULL, -- DD-MM-YYYY
    due_date TEXT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE homework ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for admissions" ON admissions;
CREATE POLICY "Allow all for admissions" ON admissions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for homework" ON homework;
CREATE POLICY "Allow all for homework" ON homework FOR ALL USING (true) WITH CHECK (true);

-- 7. Class Subjects Mapping Table (Many-to-Many Class to Subjects)
CREATE TABLE IF NOT EXISTS class_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class_name TEXT NOT NULL,
    subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_class_subject UNIQUE (school_id, class_name, subject_id)
);

ALTER TABLE class_subjects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for class_subjects" ON class_subjects;
CREATE POLICY "Allow all for class_subjects" ON class_subjects FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 8. NSB CASH BOOK (Form No 8)
-- ============================================================
CREATE TABLE IF NOT EXISTS nsb_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    emis TEXT,
    tehsil TEXT,
    zila TEXT,
    school_name TEXT,
    bank_name TEXT,
    account_no TEXT,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    previous_balance NUMERIC(12, 2) DEFAULT 0,
    bank_balance NUMERIC(12, 2) DEFAULT 0,
    cash_in_hand NUMERIC(12, 2) DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_nsb_settings UNIQUE (school_id, month, year)
);

CREATE TABLE IF NOT EXISTS nsb_income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    sr_no INT,
    date TEXT NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_mode TEXT DEFAULT 'چیک',
    signature TEXT DEFAULT 'منظور',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS nsb_expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    sr_no INT,
    date TEXT NOT NULL,
    receipt_no TEXT,
    description TEXT NOT NULL,
    bank_withdrawn NUMERIC(12, 2) DEFAULT 0,
    payment NUMERIC(12, 2) NOT NULL DEFAULT 0,
    approval_ref TEXT,
    signature TEXT DEFAULT 'منظور',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE nsb_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE nsb_income ENABLE ROW LEVEL SECURITY;
ALTER TABLE nsb_expense ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for nsb_settings" ON nsb_settings;
CREATE POLICY "Allow all for nsb_settings" ON nsb_settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for nsb_income" ON nsb_income;
CREATE POLICY "Allow all for nsb_income" ON nsb_income FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for nsb_expense" ON nsb_expense;
CREATE POLICY "Allow all for nsb_expense" ON nsb_expense FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 9. FTF REGISTER (فروغ تعلیم فنڈ)
-- ============================================================
CREATE TABLE IF NOT EXISTS ftf_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    markaz TEXT,
    tehsil TEXT,
    zila TEXT,
    school_name TEXT,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    babat_maah TEXT,
    previous_balance NUMERIC(12, 2) DEFAULT 0,
    cash_in_hand NUMERIC(12, 2) DEFAULT 0,
    bank_balance NUMERIC(12, 2) DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_ftf_settings UNIQUE (school_id, month, year)
);

CREATE TABLE IF NOT EXISTS ftf_fee_structure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class_name TEXT NOT NULL,
    fee_amount NUMERIC(10, 2) NOT NULL DEFAULT 20,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_ftf_fee UNIQUE (school_id, class_name)
);

CREATE TABLE IF NOT EXISTS ftf_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    class_name TEXT NOT NULL,
    student_count INT NOT NULL DEFAULT 0,
    fee_per_student NUMERIC(10, 2) NOT NULL DEFAULT 20,
    total_collected NUMERIC(12, 2) NOT NULL DEFAULT 0,
    teacher_signature TEXT,
    receiver_signature TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_ftf_collection UNIQUE (school_id, month, year, class_name)
);

CREATE TABLE IF NOT EXISTS ftf_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    year TEXT NOT NULL,
    date TEXT NOT NULL,
    tafseel TEXT NOT NULL,
    raqam NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ftf_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE ftf_fee_structure ENABLE ROW LEVEL SECURITY;
ALTER TABLE ftf_collection ENABLE ROW LEVEL SECURITY;
ALTER TABLE ftf_expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for ftf_settings" ON ftf_settings;
CREATE POLICY "Allow all for ftf_settings" ON ftf_settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for ftf_fee_structure" ON ftf_fee_structure;
CREATE POLICY "Allow all for ftf_fee_structure" ON ftf_fee_structure FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for ftf_collection" ON ftf_collection;
CREATE POLICY "Allow all for ftf_collection" ON ftf_collection FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for ftf_expenses" ON ftf_expenses;
CREATE POLICY "Allow all for ftf_expenses" ON ftf_expenses FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 10. SCHOOL STOCK & STORE INVENTORY SYSTEM
-- ============================================================
CREATE TABLE IF NOT EXISTS stock_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_stock_category UNIQUE (school_id, name)
);

CREATE TABLE IF NOT EXISTS stock_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    location_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_stock_location UNIQUE (school_id, location_name)
);

CREATE TABLE IF NOT EXISTS stock_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES stock_categories(id) ON DELETE SET NULL,
    item_name TEXT NOT NULL,
    unit TEXT DEFAULT 'عدد', -- عدد, سیٹ, کلو, میٹر, ڈبہ
    purchase_price NUMERIC(12, 2) DEFAULT 0,
    total_quantity INT DEFAULT 0,
    current_quantity INT DEFAULT 0,
    min_limit INT DEFAULT 5,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stock_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    item_id BIGINT REFERENCES stock_items(id) ON DELETE CASCADE,
    quantity_in INT NOT NULL,
    price_per_unit NUMERIC(12, 2) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    vendor_name TEXT,
    bill_no TEXT,
    purchase_date TEXT NOT NULL, -- DD-MM-YYYY
    added_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stock_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    item_id BIGINT REFERENCES stock_items(id) ON DELETE CASCADE,
    quantity_out INT NOT NULL,
    issued_to_type TEXT DEFAULT 'Room', -- Class, Room, Office, Lab, Teacher, Student, Other
    issued_to_id TEXT,
    issued_to_name TEXT NOT NULL, -- e.g. Class 5, Room No 3, Staff Room, Head Office
    location_name TEXT,
    purpose TEXT,
    issued_by TEXT,
    issue_date TEXT NOT NULL, -- DD-MM-YYYY
    returnable BOOLEAN DEFAULT FALSE,
    returned_quantity INT DEFAULT 0,
    status TEXT DEFAULT 'issued', -- issued, returned, damaged
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE stock_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_issues ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for stock_categories" ON stock_categories;
CREATE POLICY "Allow all for stock_categories" ON stock_categories FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for stock_locations" ON stock_locations;
CREATE POLICY "Allow all for stock_locations" ON stock_locations FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for stock_items" ON stock_items;
CREATE POLICY "Allow all for stock_items" ON stock_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for stock_purchases" ON stock_purchases;
CREATE POLICY "Allow all for stock_purchases" ON stock_purchases FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for stock_issues" ON stock_issues;
CREATE POLICY "Allow all for stock_issues" ON stock_issues FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 11. TIMETABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS timetable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class_name TEXT NOT NULL,
    day_of_week TEXT NOT NULL, -- Monday, Tuesday, Wednesday, Thursday, Friday, Saturday
    period_no INT NOT NULL, -- 1 to 8
    subject_name TEXT NOT NULL,
    teacher_name TEXT,
    room_no TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_class_day_period UNIQUE(school_id, class_name, day_of_week, period_no)
);

ALTER TABLE timetable ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for timetable" ON timetable;
CREATE POLICY "Allow all for timetable" ON timetable FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 12. CERTIFICATES
-- ============================================================
CREATE TABLE IF NOT EXISTS certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    cert_type TEXT NOT NULL, -- leaving, character, merit, sports
    cert_no TEXT NOT NULL,
    issue_date TEXT NOT NULL, -- DD-MM-YYYY
    conduct TEXT DEFAULT 'Excellent',
    reason_for_leaving TEXT,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for certificates" ON certificates;
CREATE POLICY "Allow all for certificates" ON certificates FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 13. TRANSPORT
-- ============================================================
CREATE TABLE IF NOT EXISTS transport_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    route_name TEXT NOT NULL,
    vehicle_no TEXT NOT NULL,
    driver_name TEXT NOT NULL,
    driver_phone TEXT,
    monthly_fee NUMERIC(10, 2) DEFAULT 0,
    capacity INT DEFAULT 30,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transport_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    route_id BIGINT REFERENCES transport_routes(id) ON DELETE CASCADE,
    pickup_point TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE transport_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE transport_allocations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for transport_routes" ON transport_routes;
CREATE POLICY "Allow all for transport_routes" ON transport_routes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for transport_allocations" ON transport_allocations;
CREATE POLICY "Allow all for transport_allocations" ON transport_allocations FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 14. LIBRARY
-- ============================================================
CREATE TABLE IF NOT EXISTS library_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    author TEXT,
    isbn TEXT,
    category TEXT,
    total_copies INT DEFAULT 1,
    available_copies INT DEFAULT 1,
    rack_no TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS library_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    book_id BIGINT REFERENCES library_books(id) ON DELETE CASCADE,
    borrower_type TEXT DEFAULT 'student', -- student, teacher
    borrower_id BIGINT,
    borrower_name TEXT NOT NULL,
    issue_date TEXT NOT NULL,
    due_date TEXT NOT NULL,
    return_date TEXT,
    status TEXT DEFAULT 'issued', -- issued, returned, lost
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE library_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE library_issues ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for library_books" ON library_books;
CREATE POLICY "Allow all for library_books" ON library_books FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 15. SCHOOL PROFILE EXTENSIONS (FOR 100% DYNAMIC BRANDING & ACCOUNTS)
-- ============================================================
ALTER TABLE schools ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS principal_name TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS easypaisa_no TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS easypaisa_title TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS jazzcash_no TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS jazzcash_title TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS bank_account TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS bank_title TEXT;

-- ============================================================
-- 16. PARENT MESSAGES LOG (WHATSAPP PORTAL)
-- ============================================================
CREATE TABLE IF NOT EXISTS parent_messages_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('absent', 'fee_paid', 'fee_due', 'result', 'general')),
    recipient_phone TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'sent', -- 'sent', 'pending', 'failed'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE parent_messages_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for parent_messages_log" ON parent_messages_log;
CREATE POLICY "Allow all for parent_messages_log" ON parent_messages_log FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 17. ONLINE PAYMENTS (EASYPAISA / JAZZCASH / QR VERIFICATION)
-- ============================================================
CREATE TABLE IF NOT EXISTS online_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    challan_no TEXT,
    transaction_id TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    method TEXT NOT NULL CHECK (method IN ('easypaisa', 'jazzcash', 'bank', 'cash')),
    sender_phone TEXT,
    proof_image TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'rejected')),
    notes TEXT,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 18. STAFF PAYROLL & SALARIES (FROM ATTENDANCE)
-- ============================================================
CREATE TABLE IF NOT EXISTS staff_salaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    staff_id BIGINT REFERENCES teachers(id) ON DELETE CASCADE,
    month_year TEXT NOT NULL, -- e.g. 'Oct-2026'
    basic_salary NUMERIC(10, 2) NOT NULL DEFAULT 0,
    present_days INT NOT NULL DEFAULT 0,
    absent_days INT NOT NULL DEFAULT 0,
    deduction NUMERIC(10, 2) NOT NULL DEFAULT 0,
    bonus NUMERIC(10, 2) NOT NULL DEFAULT 0,
    net_salary NUMERIC(10, 2) NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    paid_date TEXT, -- DD-MM-YYYY
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_staff_salary_month UNIQUE(school_id, staff_id, month_year)
);

CREATE TABLE IF NOT EXISTS teacher_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE CASCADE,
    date TEXT NOT NULL, -- DD-MM-YYYY
    month_year TEXT NOT NULL, -- e.g. 'Oct-2026'
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent', 'Leave')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_teacher_attendance_per_day UNIQUE(school_id, teacher_id, date)
);

ALTER TABLE staff_salaries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for staff_salaries" ON staff_salaries;
CREATE POLICY "Allow all for staff_salaries" ON staff_salaries FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE teacher_attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for teacher_attendance" ON teacher_attendance;
CREATE POLICY "Allow all for teacher_attendance" ON teacher_attendance FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 19. ADMISSION APPLICATIONS TABLE (TABLE ALIAS FOR ONLINE ADMISSIONS)
-- ============================================================
CREATE TABLE IF NOT EXISTS admission_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_name TEXT NOT NULL,
    father_name TEXT NOT NULL,
    dob TEXT,
    gender TEXT,
    class_applying TEXT NOT NULL,
    previous_school TEXT,
    phone TEXT NOT NULL,
    address TEXT,
    photo_url TEXT,
    data JSONB DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    rejection_reason TEXT,
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admission_applications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for admission_applications" ON admission_applications;
CREATE POLICY "Allow all for admission_applications" ON admission_applications FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- 20. HOMEWORKS TABLE (TABLE ALIAS FOR HOMEWORK DIARY)
-- ============================================================
CREATE TABLE IF NOT EXISTS homeworks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class_id TEXT,
    class TEXT NOT NULL,
    subject TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    date TEXT NOT NULL, -- DD-MM-YYYY
    due_date TEXT,
    attachment_url TEXT,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE homeworks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for homeworks" ON homeworks;
CREATE POLICY "Allow all for homeworks" ON homeworks FOR ALL USING (true) WITH CHECK (true);



