-- ============================================================
-- SQL SCHEMA FOR NEW FEATURES: ATTENDANCE, EXAMS, SUBJECTS, MARKS
-- Run this in your Supabase SQL Editor
-- ============================================================

-- 1. Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    date TEXT NOT NULL, -- Format DD-MM-YYYY
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent', 'Leave')),
    marked_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_student_attendance_per_day UNIQUE(school_id, student_id, date)
);

-- 2. Exams Table
CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    exam_name TEXT NOT NULL,
    term TEXT,
    class TEXT,
    date TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT,
    category TEXT DEFAULT 'Compulsory',
    total_marks NUMERIC(6, 2) DEFAULT 100,
    passing_marks NUMERIC(6, 2) DEFAULT 33,
    class TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_school_subject_name UNIQUE (school_id, name)
);

-- 4. Marks Table
CREATE TABLE IF NOT EXISTS marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    exam_id BIGINT REFERENCES exams(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
    total_marks NUMERIC(6, 2) NOT NULL DEFAULT 100,
    obtained_marks NUMERIC(6, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_student_exam_subject_mark UNIQUE(school_id, student_id, exam_id, subject_id)
);

-- Enable RLS & Policies
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE marks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for attendance" ON attendance;
CREATE POLICY "Allow all for attendance" ON attendance FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for exams" ON exams;
CREATE POLICY "Allow all for exams" ON exams FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for subjects" ON subjects;
CREATE POLICY "Allow all for subjects" ON subjects FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for marks" ON marks;
CREATE POLICY "Allow all for marks" ON marks FOR ALL USING (true) WITH CHECK (true);

-- 5. Admissions Table (Public Online Admission Form)
CREATE TABLE IF NOT EXISTS admissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_name TEXT NOT NULL,
    father_name TEXT NOT NULL,
    dob TEXT,
    gender TEXT,
    class_applying TEXT NOT NULL,
    previous_school TEXT,
    phone TEXT NOT NULL,
    address TEXT,
    photo_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, approved, rejected
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Homework Diary Table
CREATE TABLE IF NOT EXISTS homework (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    class TEXT NOT NULL,
    subject TEXT NOT NULL,
    date TEXT NOT NULL, -- DD-MM-YYYY
    due_date TEXT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE homework ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for admissions" ON admissions;
CREATE POLICY "Allow all for admissions" ON admissions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for homework" ON homework;
CREATE POLICY "Allow all for homework" ON homework FOR ALL USING (true) WITH CHECK (true);

